Python/Django/Django/my_first_site/cars/urls.py
from django.urls import path
from . import views

app_name = "cars"

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('reviews/', views.reviews, name='reviews'),
    path('thanks/', views.thanks, name='thanks')
]

Python/Django/Django/my_first_site/my_first_app/urls.py
from django.urls import path
from . import views

app_name = 'my_first_app'

urlpatterns = [
    path('',views.simple_view,name='simple_view'),
    path('<int:num_page>', views.num_page_view),
    #path('<str:topic>', views.news_view,name="topic-page"),
    path('variable/', views.variable_view, name='variable'),
    #path('<int:num1>/<int:num2>', views.add_view),
    path('basehtml', views.base_html)
]

Python/Django/Django/my_first_site/my_first_site/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('my_first_app/',include('my_first_app.urls')),
    path('admin/', admin.site.urls),
    path('office/', include('office.urls')),
    path('cars/', include('cars.urls')),
    path('classroom/', include('classroom.urls')),
    path('', views.home_view)
]

from django.conf.urls import handler404

handler404 = "my_first_site.views.custom_404_view"

Python/Django/Django/my_first_site/templates/first_app/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is above the block</h1>
    {% block content %}
    
    {% endblock content %}
    <h1>This is below the block</h1>
</body>
</html>

Python/Django/Django/my_first_site/templates/first_app/example-inherit.html
{% extends 'first_app/base.html' %}

{% load static %}

{% block content %}
    <h1>This is inside the block</h1>
    <img src="{% static 'my_first_app/osi.png' %}" alt='hehe'>
{% endblock content %}

Python/Django/Django/my_first_site/templates/first_app/example.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Example html connected</h1>
    <h1><a href="{% url 'my_first_app:variable' %}">CLICK HERE</a></h1>
</body>
</html>

Python/Django/Django/my_first_site/templates/first_app/example2.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>VARIABLE.HTML</h1>
    <h2>{{first_name | lower | capfirst}}</h2>
    <h2>{{some_list.0}}</h2>
    <h2>{{some_dict.inside_key}}</h2>
    <!-- This is a comment -->
    <ul>
    {% for item in some_list %}
        <li>{{item}}</li>
    {% endfor %}
    </ul>
    <ul>
        {% for k,v in some_dict.items %}
            <li>{{v}}</li>
        {% endfor %}
    </ul>
    {% if user_logged_in and first_name == "Rosaline" %}
        <h1>Welcome back, {{first_name}}!</h1>
    {% endif %}
    {% for num in some_list %}
        {% if num == 2 %}
            <li>The two</li>
        {% else %}
            <li>{{num}}</li>
        {% endif %}
    {% endfor %}
</body>
</html>