Python/Django/Django/my_first_site/cars/urls.py
from django.urls import path
from . import views

app_name = "cars"

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('reviews/', views.reviews, name='reviews'),
    path('thanks/', views.thanks, name='thanks')
]

Python/Django/Django/my_first_site/classroom/urls.py
from django.urls import path
from .views import (HomeView, ThankYouView, ContactFormView, 
                    TeacherCreateView, TeacherListView,
                    TeacherDetailView, TeacherUpdateView,
                    TeacherDeleteView)

app_name = "classroom"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('thanks/', ThankYouView.as_view(), name='thanks'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('teacher_detail/<int:pk>', TeacherDetailView.as_view(), name="detail_teacher"),
    path('teacher_list/', TeacherListView.as_view(), name="teacher_list"),
    path('update_teacher/<int:pk>', TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>', TeacherDeleteView.as_view(), name="delete_teacher")
]   

Python/Django/Django/my_first_site/my_first_site/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('my_first_app/',include('my_first_app.urls')),
    path('admin/', admin.site.urls),
    path('office/', include('office.urls')),
    path('cars/', include('cars.urls')),
    path('classroom/', include('classroom.urls')),
    path('', views.home_view)
]

from django.conf.urls import handler404

handler404 = "my_first_site.views.custom_404_view"

Python/Django/Django/my_first_site/classroom/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

Python/Django/Django/my_first_site/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

Python/Django/Django/my_first_site/classroom/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, FormView, CreateView
                                  , ListView, DetailView, UpdateView,
                                  DeleteView)
from .forms import ContactForm
from django.urls import reverse, reverse_lazy
from classroom.models import Teacher

# Create your views here.
def home_view(request):
    return render(request, 'classroom/home.html')

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thanks.html'

class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:thanks')

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    # URL that you want to redirect to
    # success_url = "/classroom/thanks/"
    success_url = reverse_lazy('classroom:thanks')
    # What to do with form
    #def form_valid(self, form):
    #    print(form.cleaned_data)

        # similar to ContactForm(request.POST)
    #    return super().form_valid(form)

class TeacherListView(ListView):
    model = Teacher
    queryset = Teacher.objects.order_by("first_name")
    context_object_name = "teacher_list"

class TeacherDetailView(DetailView):
    # model should be called model_detail.html
    model = Teacher

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:teacher_list')

class TeacherDeleteView(DeleteView):
    # Form --> Confirm Delete Button
    # default template name:
    # model_confirm_delete.html
    model = Teacher
    success_url = reverse_lazy('classroom:teacher_list')

Python/Django/Django/my_first_site/classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

Python/Django/Django/my_first_site/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>
<ul>
    <li>
        <a href="{% url 'classroom:thanks' %}">Thank you page</a>
    </li>
    <li>
        <a href="{% url 'classroom:contact' %}">Contact page</a>
    </li>
    <li>
        <a href="{% url 'classroom:create_teacher' %}">Create new teacher page</a>
    </li>
    <li>
        <a href="{% url 'classroom:teacher_list' %}">List teacher page</a>
    </li>
</ul>

Python/Django/Django/my_first_site/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure want to delete this teacher?</h1>
<h2>{{teacher}}</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

Python/Django/Django/my_first_site/classroom/templates/classroom/teacher_detail.html
<h1>Detail View for a Teacher</h1>
{{teacher}}

Python/Django/Django/my_first_site/classroom/templates/classroom/teacher_form.html
<h1>Teacher form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

Python/Django/Django/my_first_site/classroom/templates/classroom/teacher_list.html
<h1>List of Teacher (ListView)</h1>
<ul>
    {% for teacher in teacher_list %}
        <li><a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</li>
        <ul>
            <li>
                <a href="/classroom/update_teacher/{{teacher.id}}">Update Information for {{teacher.first_name}}
            </li>
        </ul>    
        <ul>
            <li>
                <a href="/classroom/delete_teacher/{{teacher.id}}">Delete {{teacher.first_name}}
            </li>
        </ul>
            
    {% endfor %}
</ul>

Python/Django/Django/my_first_site/classroom/templates/classroom/thanks.html
<h1>Thank You!</h1>