Python/Django/Django/my_first_site/cars/urls.py
from django.urls import path
from . import views

app_name = "cars"

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('reviews/', views.reviews, name='reviews'),
    path('thanks/', views.thanks, name='thanks')
]

Python/Django/Django/my_first_site/my_first_site/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('my_first_app/',include('my_first_app.urls')),
    path('admin/', admin.site.urls),
    path('office/', include('office.urls')),
    path('cars/', include('cars.urls')),
    path('classroom/', include('classroom.urls')),
    path('', views.home_view)
]

from django.conf.urls import handler404

handler404 = "my_first_site.views.custom_404_view"

Python/Django/Django/my_first_site/cars/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=50)
    year = models.IntegerField()
    def __str__(self) -> str:
        return f"Car is {self.brand} {self.year}"
    
class Review(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

Python/Django/Django/my_first_site/cars/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm

'''
class ReviewForm(forms.Form):
    first_name = forms.CharField(label="First Name", max_length=100)
    last_name = forms.CharField(label="Last Name", max_length=100)
    email = forms.EmailField(label="Last Name", max_length=100)
    review = forms.CharField(label="Please write your review here", widget=forms.Textarea(attrs={'class':'myform','rows':'2','cols':'2'}))
    '''

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = "__all__" # pass in all model fields as form field
        labels = {
            'first_name':"YOUR FIRST NAME",
            'last_name':"Last Name",
            'stars':"Rating"
        }

        error_messages = {
            'stars': {
                'min_value':"Min value is 1",
                'max_value':"Max value is 5"
            }
        }

Python/Django/Django/my_first_site/cars/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse
from .forms import ReviewForm

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars':all_cars}
    return render(request,'cars/list.html',context=context)

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    else:
        return render(request,'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse("cars:list"))
        except:
            print("PK not found!")
            return redirect(reverse("cars:list"))
    else:
        return render(request,'cars/delete.html')

def reviews(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("cars:thanks"))
    else:
        form = ReviewForm()
    return render(request, "cars/reviews.html",context={"form":form})

def thanks(request):
    return render(request, "cars/thanks.html")

Python/Django/Django/my_first_site/templates/cars/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
<body>
    <!--NAVBAR-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
                        <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
                        <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
                    </div>
                </div>
            </div>
        </nav>
    {% block content %}
        
    {% endblock content %}
</body>
</html>